---
  - hosts: webServers
    become: yes
    remote_user: ubuntu

    vars:
       deploy_directory: '/home/ubuntu/bootcamp-app'

    tasks:
    - name: update ubuntu server
      shell: apt-get update

    - name: Update nodejs package
      shell: curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
 
    - name: Install nodejs
      apt:
        name: nodejs
        state: present
 
    - name: Install pm2
      shell: npm install pm2 -g
 
 
    - name: Git Clone Repo
      git: repo="https://github.com/barak98/bootcamp-app.git" dest={{ deploy_directory }}/ update=yes force=yes accept_hostkey=yes
      register: git_finished
 
    - name: Npm initialization
      shell: npm init -y
      args:
        chdir: '{{ deploy_directory }}/'
 
 
    - name: Running NPM install
      shell: npm install
      register: npm_finished
      when: git_finished.changed
      args:
        chdir: '{{ deploy_directory }}/'

    
    - name: copying file with playbook
      copy:
        dest: '{{ deploy_directory }}/.env'
        content: |
         PORT=8080
         HOST='0.0.0.0'
         HOST_URL=http://{{added manually}}:8080
         COOKIE_ENCRYPT_PWD=superAwesomePasswordStringThatIsAtLeast32CharactersLong!
         NODE_ENV=development
         OKTA_ORG_URL={{added manually}}
         OKTA_CLIENT_ID={{added manually}}
         OKTA_CLIENT_SECRET={{added manually}}
         PGHOST={{added manually}}
         PGUSERNAME={{added manually}}
         PGDATABASE={{added manually}}
         PGPASSWORD={{added manually}}
         PGPORT=5432

 
 
    - name: Init DB
      shell: npm run initdb
      async: 30
      poll: 0
      args:
        chdir: '{{ deploy_directory }}/'
 
    - name: Clear pm2
      shell: pm2 delete all
      ignore_errors: yes
 
    - name: Start APP
      shell: pm2 start npm -- run dev pm2 save && pm2 startup
      args:
        chdir: '{{ deploy_directory }}/'